// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResourceTracker.proto

package com.tan.hadoop.rpc.proto;

public final class ResourceTracker {
  private ResourceTracker() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf service {@code ResourceTrackerService}
   */
  public static abstract class ResourceTrackerService
      implements com.google.protobuf.Service {
    protected ResourceTrackerService() {}

    public interface Interface {
      /**
       * <code>rpc registerNodeManager(.RequestProto) returns (.ResponseProto);</code>
       */
      public abstract void registerNodeManager(
          com.google.protobuf.RpcController controller,
          com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto request,
          com.google.protobuf.RpcCallback<com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new ResourceTrackerService() {
        @java.lang.Override
        public  void registerNodeManager(
            com.google.protobuf.RpcController controller,
            com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto request,
            com.google.protobuf.RpcCallback<com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto> done) {
          impl.registerNodeManager(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.registerNodeManager(controller, (com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc registerNodeManager(.RequestProto) returns (.ResponseProto);</code>
     */
    public abstract void registerNodeManager(
        com.google.protobuf.RpcController controller,
        com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto request,
        com.google.protobuf.RpcCallback<com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.tan.hadoop.rpc.proto.ResourceTracker.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.registerNodeManager(controller, (com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto)request,
            com.google.protobuf.RpcUtil.<com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.tan.hadoop.rpc.proto.ResourceTracker.ResourceTrackerService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void registerNodeManager(
          com.google.protobuf.RpcController controller,
          com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto request,
          com.google.protobuf.RpcCallback<com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto.class,
            com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto registerNodeManager(
          com.google.protobuf.RpcController controller,
          com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto registerNodeManager(
          com.google.protobuf.RpcController controller,
          com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto request)
          throws com.google.protobuf.ServiceException {
        return (com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:ResourceTrackerService)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ResourceTracker.proto\032\034ResourceTracker" +
      "Message.proto2N\n\026ResourceTrackerService\022" +
      "4\n\023registerNodeManager\022\r.RequestProto\032\016." +
      "ResponseProtoB1\n\030com.tan.hadoop.rpc.prot" +
      "oB\017ResourceTracker\210\001\001\240\001\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tan.hadoop.rpc.proto.ResourceTrackerMessage.getDescriptor(),
        });
    com.tan.hadoop.rpc.proto.ResourceTrackerMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
