// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResourceTrackerMessage.proto

package com.tan.hadoop.rpc.proto;

public final class ResourceTrackerMessage {
  private ResourceTrackerMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string hostname = 1;</code>
     * @return Whether the hostname field is set.
     */
    boolean hasHostname();
    /**
     * <code>required string hostname = 1;</code>
     * @return The hostname.
     */
    java.lang.String getHostname();
    /**
     * <code>required string hostname = 1;</code>
     * @return The bytes for hostname.
     */
    com.google.protobuf.ByteString
        getHostnameBytes();

    /**
     * <code>required int32 cpu = 2;</code>
     * @return Whether the cpu field is set.
     */
    boolean hasCpu();
    /**
     * <code>required int32 cpu = 2;</code>
     * @return The cpu.
     */
    int getCpu();

    /**
     * <code>required int32 memory = 3;</code>
     * @return Whether the memory field is set.
     */
    boolean hasMemory();
    /**
     * <code>required int32 memory = 3;</code>
     * @return The memory.
     */
    int getMemory();
  }
  /**
   * Protobuf type {@code RequestProto}
   */
  public static final class RequestProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestProto)
      RequestProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestProto.newBuilder() to construct.
    private RequestProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestProto() {
      hostname_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RequestProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              hostname_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cpu_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              memory_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tan.hadoop.rpc.proto.ResourceTrackerMessage.internal_static_RequestProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tan.hadoop.rpc.proto.ResourceTrackerMessage.internal_static_RequestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto.class, com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto.Builder.class);
    }

    private int bitField0_;
    public static final int HOSTNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object hostname_;
    /**
     * <code>required string hostname = 1;</code>
     * @return Whether the hostname field is set.
     */
    @java.lang.Override
    public boolean hasHostname() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string hostname = 1;</code>
     * @return The hostname.
     */
    @java.lang.Override
    public java.lang.String getHostname() {
      java.lang.Object ref = hostname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hostname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string hostname = 1;</code>
     * @return The bytes for hostname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHostnameBytes() {
      java.lang.Object ref = hostname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CPU_FIELD_NUMBER = 2;
    private int cpu_;
    /**
     * <code>required int32 cpu = 2;</code>
     * @return Whether the cpu field is set.
     */
    @java.lang.Override
    public boolean hasCpu() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 cpu = 2;</code>
     * @return The cpu.
     */
    @java.lang.Override
    public int getCpu() {
      return cpu_;
    }

    public static final int MEMORY_FIELD_NUMBER = 3;
    private int memory_;
    /**
     * <code>required int32 memory = 3;</code>
     * @return Whether the memory field is set.
     */
    @java.lang.Override
    public boolean hasMemory() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 memory = 3;</code>
     * @return The memory.
     */
    @java.lang.Override
    public int getMemory() {
      return memory_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHostname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCpu()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMemory()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hostname_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, cpu_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, memory_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hostname_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cpu_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, memory_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto)) {
        return super.equals(obj);
      }
      com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto other = (com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto) obj;

      if (hasHostname() != other.hasHostname()) return false;
      if (hasHostname()) {
        if (!getHostname()
            .equals(other.getHostname())) return false;
      }
      if (hasCpu() != other.hasCpu()) return false;
      if (hasCpu()) {
        if (getCpu()
            != other.getCpu()) return false;
      }
      if (hasMemory() != other.hasMemory()) return false;
      if (hasMemory()) {
        if (getMemory()
            != other.getMemory()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHostname()) {
        hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getHostname().hashCode();
      }
      if (hasCpu()) {
        hash = (37 * hash) + CPU_FIELD_NUMBER;
        hash = (53 * hash) + getCpu();
      }
      if (hasMemory()) {
        hash = (37 * hash) + MEMORY_FIELD_NUMBER;
        hash = (53 * hash) + getMemory();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestProto)
        com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tan.hadoop.rpc.proto.ResourceTrackerMessage.internal_static_RequestProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tan.hadoop.rpc.proto.ResourceTrackerMessage.internal_static_RequestProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto.class, com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto.Builder.class);
      }

      // Construct using com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        hostname_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        cpu_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        memory_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tan.hadoop.rpc.proto.ResourceTrackerMessage.internal_static_RequestProto_descriptor;
      }

      @java.lang.Override
      public com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto getDefaultInstanceForType() {
        return com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto.getDefaultInstance();
      }

      @java.lang.Override
      public com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto build() {
        com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto buildPartial() {
        com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto result = new com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hostname_ = hostname_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.cpu_ = cpu_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.memory_ = memory_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto) {
          return mergeFrom((com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto other) {
        if (other == com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto.getDefaultInstance()) return this;
        if (other.hasHostname()) {
          bitField0_ |= 0x00000001;
          hostname_ = other.hostname_;
          onChanged();
        }
        if (other.hasCpu()) {
          setCpu(other.getCpu());
        }
        if (other.hasMemory()) {
          setMemory(other.getMemory());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasHostname()) {
          return false;
        }
        if (!hasCpu()) {
          return false;
        }
        if (!hasMemory()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object hostname_ = "";
      /**
       * <code>required string hostname = 1;</code>
       * @return Whether the hostname field is set.
       */
      public boolean hasHostname() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string hostname = 1;</code>
       * @return The hostname.
       */
      public java.lang.String getHostname() {
        java.lang.Object ref = hostname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            hostname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string hostname = 1;</code>
       * @return The bytes for hostname.
       */
      public com.google.protobuf.ByteString
          getHostnameBytes() {
        java.lang.Object ref = hostname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hostname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string hostname = 1;</code>
       * @param value The hostname to set.
       * @return This builder for chaining.
       */
      public Builder setHostname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        hostname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string hostname = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHostname() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hostname_ = getDefaultInstance().getHostname();
        onChanged();
        return this;
      }
      /**
       * <code>required string hostname = 1;</code>
       * @param value The bytes for hostname to set.
       * @return This builder for chaining.
       */
      public Builder setHostnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        hostname_ = value;
        onChanged();
        return this;
      }

      private int cpu_ ;
      /**
       * <code>required int32 cpu = 2;</code>
       * @return Whether the cpu field is set.
       */
      @java.lang.Override
      public boolean hasCpu() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 cpu = 2;</code>
       * @return The cpu.
       */
      @java.lang.Override
      public int getCpu() {
        return cpu_;
      }
      /**
       * <code>required int32 cpu = 2;</code>
       * @param value The cpu to set.
       * @return This builder for chaining.
       */
      public Builder setCpu(int value) {
        bitField0_ |= 0x00000002;
        cpu_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cpu = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCpu() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cpu_ = 0;
        onChanged();
        return this;
      }

      private int memory_ ;
      /**
       * <code>required int32 memory = 3;</code>
       * @return Whether the memory field is set.
       */
      @java.lang.Override
      public boolean hasMemory() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int32 memory = 3;</code>
       * @return The memory.
       */
      @java.lang.Override
      public int getMemory() {
        return memory_;
      }
      /**
       * <code>required int32 memory = 3;</code>
       * @param value The memory to set.
       * @return This builder for chaining.
       */
      public Builder setMemory(int value) {
        bitField0_ |= 0x00000004;
        memory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 memory = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemory() {
        bitField0_ = (bitField0_ & ~0x00000004);
        memory_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RequestProto)
    }

    // @@protoc_insertion_point(class_scope:RequestProto)
    private static final com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto();
    }

    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RequestProto>
        PARSER = new com.google.protobuf.AbstractParser<RequestProto>() {
      @java.lang.Override
      public RequestProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tan.hadoop.rpc.proto.ResourceTrackerMessage.RequestProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string flag = 1;</code>
     * @return Whether the flag field is set.
     */
    boolean hasFlag();
    /**
     * <code>required string flag = 1;</code>
     * @return The flag.
     */
    java.lang.String getFlag();
    /**
     * <code>required string flag = 1;</code>
     * @return The bytes for flag.
     */
    com.google.protobuf.ByteString
        getFlagBytes();
  }
  /**
   * Protobuf type {@code ResponseProto}
   */
  public static final class ResponseProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponseProto)
      ResponseProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseProto.newBuilder() to construct.
    private ResponseProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseProto() {
      flag_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResponseProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              flag_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tan.hadoop.rpc.proto.ResourceTrackerMessage.internal_static_ResponseProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tan.hadoop.rpc.proto.ResourceTrackerMessage.internal_static_ResponseProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto.class, com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto.Builder.class);
    }

    private int bitField0_;
    public static final int FLAG_FIELD_NUMBER = 1;
    private volatile java.lang.Object flag_;
    /**
     * <code>required string flag = 1;</code>
     * @return Whether the flag field is set.
     */
    @java.lang.Override
    public boolean hasFlag() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string flag = 1;</code>
     * @return The flag.
     */
    @java.lang.Override
    public java.lang.String getFlag() {
      java.lang.Object ref = flag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          flag_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string flag = 1;</code>
     * @return The bytes for flag.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFlagBytes() {
      java.lang.Object ref = flag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        flag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFlag()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, flag_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, flag_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto)) {
        return super.equals(obj);
      }
      com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto other = (com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto) obj;

      if (hasFlag() != other.hasFlag()) return false;
      if (hasFlag()) {
        if (!getFlag()
            .equals(other.getFlag())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFlag()) {
        hash = (37 * hash) + FLAG_FIELD_NUMBER;
        hash = (53 * hash) + getFlag().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseProto)
        com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tan.hadoop.rpc.proto.ResourceTrackerMessage.internal_static_ResponseProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tan.hadoop.rpc.proto.ResourceTrackerMessage.internal_static_ResponseProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto.class, com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto.Builder.class);
      }

      // Construct using com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        flag_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tan.hadoop.rpc.proto.ResourceTrackerMessage.internal_static_ResponseProto_descriptor;
      }

      @java.lang.Override
      public com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto getDefaultInstanceForType() {
        return com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto.getDefaultInstance();
      }

      @java.lang.Override
      public com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto build() {
        com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto buildPartial() {
        com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto result = new com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.flag_ = flag_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto) {
          return mergeFrom((com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto other) {
        if (other == com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto.getDefaultInstance()) return this;
        if (other.hasFlag()) {
          bitField0_ |= 0x00000001;
          flag_ = other.flag_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasFlag()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object flag_ = "";
      /**
       * <code>required string flag = 1;</code>
       * @return Whether the flag field is set.
       */
      public boolean hasFlag() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string flag = 1;</code>
       * @return The flag.
       */
      public java.lang.String getFlag() {
        java.lang.Object ref = flag_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            flag_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string flag = 1;</code>
       * @return The bytes for flag.
       */
      public com.google.protobuf.ByteString
          getFlagBytes() {
        java.lang.Object ref = flag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          flag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string flag = 1;</code>
       * @param value The flag to set.
       * @return This builder for chaining.
       */
      public Builder setFlag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        flag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string flag = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFlag() {
        bitField0_ = (bitField0_ & ~0x00000001);
        flag_ = getDefaultInstance().getFlag();
        onChanged();
        return this;
      }
      /**
       * <code>required string flag = 1;</code>
       * @param value The bytes for flag to set.
       * @return This builder for chaining.
       */
      public Builder setFlagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        flag_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResponseProto)
    }

    // @@protoc_insertion_point(class_scope:ResponseProto)
    private static final com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto();
    }

    public static com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ResponseProto>
        PARSER = new com.google.protobuf.AbstractParser<ResponseProto>() {
      @java.lang.Override
      public ResponseProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tan.hadoop.rpc.proto.ResourceTrackerMessage.ResponseProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034ResourceTrackerMessage.proto\"=\n\014Reques" +
      "tProto\022\020\n\010hostname\030\001 \002(\t\022\013\n\003cpu\030\002 \002(\005\022\016\n" +
      "\006memory\030\003 \002(\005\"\035\n\rResponseProto\022\014\n\004flag\030\001" +
      " \002(\tB8\n\030com.tan.hadoop.rpc.protoB\026Resour" +
      "ceTrackerMessage\210\001\001\240\001\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RequestProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestProto_descriptor,
        new java.lang.String[] { "Hostname", "Cpu", "Memory", });
    internal_static_ResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseProto_descriptor,
        new java.lang.String[] { "Flag", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
